export type EmotionalLogicPreset = {
  id: string;
  name: string;
  description: string;
  wound: string;
  armor: string;
  crackInArmor: string;
  contradiction: string;
};

export const EMOTIONAL_LOGIC_PRESETS: EmotionalLogicPreset[] = [
  {
    id: "abandonment",
    name: "Abandonment",
    description: "Left by someone who chose to go",
    wound: "Left by a parent or partner who chose to go",
    armor: "Leaves before she can be left, keeps one foot out the door",
    crackInArmor: "Someone who stays after she pushes them away",
    contradiction: "Craves permanence but sabotages every relationship that offers it",
  },
  {
    id: "betrayal",
    name: "Betrayal",
    description: "Trust shattered by someone close",
    wound: "Cheated on or deeply lied to by someone she trusted completely",
    armor: "Tests people constantly, never fully believes what she's told",
    crackInArmor: "Catching someone being honest when they had every reason to lie",
    contradiction: "Wants to trust completely but builds traps to catch betrayal",
  },
  {
    id: "neglect",
    name: "Neglect",
    description: "Emotionally invisible growing up",
    wound: "Emotionally invisible growing up — no one asked how she felt",
    armor: "Over-self-sufficiency, refuses help, handles everything alone",
    crackInArmor: "Someone noticing a small thing she never mentioned — that she's tired, that she skipped lunch",
    contradiction: "Takes care of everyone but believes she doesn't deserve care herself",
  },
  {
    id: "perfectionism",
    name: "Perfectionism",
    description: "Never good enough for a critical parent",
    wound: "Never good enough for a critical parent — love was conditional on performance",
    armor: "Overachieves compulsively, curates every surface, cannot be caught slipping",
    crackInArmor: "Being caught in a messy, unpolished, imperfect moment and not being judged",
    contradiction: "Knows perfection is impossible but experiences anything less as failure",
  },
  {
    id: "loss-grief",
    name: "Loss / Grief",
    description: "Lost someone central to her world",
    wound: "Lost someone central — a parent, sibling, best friend, or child",
    armor: "Keeps emotional distance, doesn't let herself want things too much",
    crackInArmor: "Someone treating the person she lost as real — asking their name, wanting to know about them",
    contradiction: "Afraid to love fully because she knows exactly how it feels to lose",
  },
  {
    id: "rejection",
    name: "Rejection",
    description: "Repeatedly told she's too much or not enough",
    wound: "Repeatedly told she's too much, not enough, or fundamentally wrong",
    armor: "Performs confidence, curates desirability, controls how she's perceived",
    crackInArmor: "Someone wanting the version of her she hides — the weird, awkward, unstyled version",
    contradiction: "Projects total self-assurance while secretly believing she's one rejection from collapse",
  },
  {
    id: "control",
    name: "Control",
    description: "Grew up in chaos, needs to manage everything",
    wound: "Grew up in chaos — unstable home, unpredictable parent, never knew what was coming",
    armor: "Micro-manages everything, rigid routines, always has a plan and a backup plan",
    crackInArmor: "Someone creating safe spontaneity — a surprise that doesn't threaten, a change that feels exciting not dangerous",
    contradiction: "Desperately wants to let go but experiences surrender as danger",
  },
  {
    id: "shame",
    name: "Shame",
    description: "Made to feel wrong for who she is",
    wound: "Made to feel fundamentally wrong for who she is — her body, her desires, her identity",
    armor: "Hides the real self behind a curated version, code-switches constantly",
    crackInArmor: "Someone saying 'I see you' and meaning the version she hides",
    contradiction: "Performs normalcy while believing she's secretly broken",
  },
  {
    id: "enmeshment",
    name: "Enmeshment",
    description: "Overbearing parent, no sense of self",
    wound: "Overbearing parent who made her an extension of themselves — no boundaries, no separateness",
    armor: "People-pleases compulsively, has no clear sense of what she actually wants",
    crackInArmor: "Being asked 'but what do YOU want?' and someone actually waiting for the real answer",
    contradiction: "Feels suffocated by closeness but doesn't know who she is alone",
  },
  {
    id: "parentification",
    name: "Parentification",
    description: "Had to be the adult as a child",
    wound: "Had to be the adult as a child — managed siblings, parents, or the household",
    armor: "Compulsive caretaker, defines herself through what she provides for others",
    crackInArmor: "Someone taking care of HER — cooking for her, handling a problem without being asked",
    contradiction: "Gives everything to others but panics when someone tries to give back",
  },
  {
    id: "body-shame",
    name: "Body Shame",
    description: "Criticized for her appearance",
    wound: "Criticized for her appearance — too big, too flat, too dark, wrong shape, wrong everything",
    armor: "Either hyper-controls appearance or weaponizes sexuality as armor",
    crackInArmor: "Someone touching the part she hates and calling it beautiful — and meaning it",
    contradiction: "Knows she's attractive (men tell her) but doesn't believe it in her bones",
  },
  {
    id: "financial-insecurity",
    name: "Financial Insecurity",
    description: "Grew up poor or watched money destroy her family",
    wound: "Grew up poor or watched money tear her family apart",
    armor: "Either hoards security obsessively or spends recklessly to prove she's fine",
    crackInArmor: "Someone who treats her exactly the same whether she has money or not",
    contradiction: "Measures her worth in stability but can't enjoy what she's built",
  },
  {
    id: "cultural-displacement",
    name: "Cultural Displacement",
    description: "Between two worlds, never fully belonging",
    wound: "Grew up between two cultures, never fully belonging to either",
    armor: "Code-switches perfectly, performs belonging in every room she enters",
    crackInArmor: "Someone who's curious about both sides of her without exoticizing either",
    contradiction: "Wants to be seen as whole but has never felt whole herself",
  },
  {
    id: "emotional-suppression",
    name: "Emotional Suppression",
    description: "Told her feelings were weakness",
    wound: "Told her feelings were weakness, drama, or too much — learned to shut down",
    armor: "Stoic, controlled, rarely raises her voice or shows distress",
    crackInArmor: "An overwhelming emotion she can't contain — fury, lust, or grief — that leaks out despite her",
    contradiction: "Appears unshakeable while sitting on a volcano",
  },
  {
    id: "daddy-issues",
    name: "Daddy Issues",
    description: "Absent or emotionally unavailable father",
    wound: "Absent, abusive, or emotionally unavailable father who set the template for men",
    armor: "Seeks validation from men, confuses authority with safety, tests constantly",
    crackInArmor: "A man who is gentle without being asked — patient, present, not performing strength",
    contradiction: "Wants a man's approval while resenting that she wants it",
  },
  {
    id: "codependency",
    name: "Codependency",
    description: "Only felt valuable when saving someone",
    wound: "Only ever felt valuable when she was saving or fixing someone broken",
    armor: "Picks broken people, defines herself as the healer and fixer",
    crackInArmor: "Someone who doesn't need fixing but wants her anyway",
    contradiction: "Feels most alive in crisis and doesn't know what to do with stability",
  },
  {
    id: "hypervigilance",
    name: "Hypervigilance",
    description: "Grew up unsafe, always reading the room",
    wound: "Grew up unsafe — had to read rooms, moods, and micro-expressions to survive",
    armor: "Reads everyone constantly, anticipates needs, never fully relaxes",
    crackInArmor: "Falling asleep next to someone — actually falling asleep, not pretending",
    contradiction: "Can predict everyone's emotions but can't identify her own",
  },
  {
    id: "golden-child",
    name: "Golden Child",
    description: "The perfect one who can never fail",
    wound: "Was the perfect one, the achiever, the family's pride — love was the reward for performance",
    armor: "Cannot fail, cannot disappoint, maintains the image at all costs",
    crackInArmor: "Doing something purely selfish for the first time and not apologizing for it",
    contradiction: "Everyone thinks she has it together, which means no one ever asks if she's okay",
  },
  {
    id: "scapegoat",
    name: "Scapegoat",
    description: "Blamed for everything, the family's problem",
    wound: "Blamed for everything — the family's designated problem child, the one who's 'too much'",
    armor: "Leans into the bad girl role — if she's already the villain, she'll own it",
    crackInArmor: "Someone defending her to someone else when she can't overhear it",
    contradiction: "Performs not caring while memorizing every criticism word for word",
  },
  {
    id: "romantic-disillusionment",
    name: "Romantic Disillusionment",
    description: "Believed in love stories, got reality",
    wound: "Believed in fairy-tale love, got cheated on, ghosted, or slowly eroded by mediocre relationships",
    armor: "Cynical about romance, treats relationships as transactional or temporary",
    crackInArmor: "An unscripted, imperfect romantic moment she didn't see coming — and can't dismiss",
    contradiction: "Mocks romance publicly but has a hidden Pinterest board of wedding dresses",
  },
];
